pub mod app;
pub mod component;
pub mod components;
pub mod element;
pub mod elements;
pub mod escape;
pub mod frame;
pub mod hooks;
pub mod inline;
pub mod insets;
pub mod node;
pub mod renderer;
pub mod terminal;
pub mod wrap;

// Re-export key types at the crate root for convenience
pub use app::{Application, ApplicationBuilder, ControlFlow, Handle};
pub use component::{Component, EventResult, HStack, Tracked, VStack};
pub use components::markdown::{Markdown, MarkdownState};
pub use components::spinner::{Spinner, SpinnerState};
pub use components::text::TextBlock;
pub use element::{ElementHandle, Elements};
pub use escape::CursorState;
pub use frame::{Diff, Frame};
pub use hooks::Hooks;
pub use insets::Insets;
pub use inline::InlineRenderer;
pub use node::{Layout, NodeId, WidthConstraint};
pub use renderer::Renderer;
pub use terminal::Terminal;
